---
     - name: Installing tools 
       apt: name={{item}} state=present 
       with_items:
          - python-mysqldb
     - name: Install mysql-server
       apt: name=mysql-server state=present    

     - name: Ensure mysql listening on all ports
       lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address
                        line="bind-address = {{ ansible_eth0.ipv4.address }}" 
       notify: restart mysql

     - name: Ensure mysql started
       service: name=mysql state=started enabled=yes

     - name: create demo database
       mysql_db: name={{ DB_USER }} state=present login_user={{ MYSQL_USER }} login_password={{ MYSQL_PASSWORD }}

     - name: create demo user
       mysql_user: name={{ DB_USER }} password={{ DB_PASSWORD}} priv=*.*:ALL host='%' state=present login_user={{ MYSQL_USER }} login_password={{ MYSQL_PASSWORD }} 
