---
    - name: installing tools
      apt: name={{item}} state=present update_cache=yes
      with_items:
           - python-httplib2

    - apt: name=nginx state=present update_cache=yes
   
    - name: configure nginx site
      template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/{{ item.key }} mode=0644
      with_dict: "{{ sites }}"
      notify: restart nginx

    - name: list all apps
      command: ls  /etc/nginx/sites-enabled
      register: active
   
    - name: de-activate sites
      file: path=/etc/nginx/sites-enabled/{{ item }} state=absent
      with_items: ['demo' , 'myapp']
      when: item not in sites       
      notify: restart nginx             
     
    - name: setting our file in nginx
      file: src=/etc/nginx/sites-available/{{ item.key }} dest=/etc/nginx/sites-enabled/{{ item.key }} state=link
      with_dict: "{{ sites }}"
      notify: restart nginx

    - name: ensure enginx started
      service: name=nginx state=started enabled=yes
 
     