---
 - name: Install and configure tomcat
   hosts: node1.ak2328.online
   gather_facts: false
   become: true
   vars:
     req_java: jre-1.8.0-openjdk
     set_java: jre-1.8.0-openjdk
     req_tomcat_ver: 9.0.34
     tomcat_port: 8090
     tomcat_url: https://mirrors.estointernet.in/apache/tomcat/tomcat-{{req_tomcat_ver.split('.')[0]}}/v{{req_tomcat_ver}}/bin/apache-tomcat-{{req_tomcat_ver}}.tar.gz
   tasks:
     - name: Starting tomcat
       shell: nohup /usr/local/latest/bin/startup.sh 

     - name: Replacing default  port with required port
       template:
          src: server.xml.j2
          dest: /usr/local/latest/conf/server.xml