---
 - apt: name={{item}} state=present 
   with_items:
           - apache2
           - libapache2-mod-wsgi
           - python-pip
           - python-virtualenv
           - python-mysqldb

 - name: ensure wsgi enabled
   apache2_module: name=wsgi state=present
   notify: restart apache

 - name: setting path for our file
   file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
   notify: restart apache

 - name: setting our file in apache
   file: src=/etc/apache2/sites-available/demo.conf  dest=/etc/apache2/sites-enabled/demo.conf state=link
   notify: restart apache 